name: Feature Request

description: Suggest an idea for this project.

title: "[Feature]: "

labels: [ "Core" ]

projects: ["ChopLogic/1"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: feature_summary
    attributes:
      label: "Feature Summary"
      description: "Provide a clear and concise summary of the feature you want to propose."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any additional context or references related to your feature request."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ChopLogic/chop-logic-core/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
